services:
  apollo-service:
    image: gmod/apollo:release-2.8.1
    volumes:
      - "${APOLLO_DATA_VOLUME?}/jbrowse_data/:/data"
      - "${APOLLO_DATA_VOLUME?}/postgres_data:/var/lib/postgresql"
      - "${APOLLO_DATA_VOLUME?}/temp_apollo_data:/temp_apollo_data"
    environment:
      - WEBAPOLLO_COMMON_DATA=/temp_apollo_data
      # Web interface admin credentials
      - APOLLO_ADMIN_EMAIL=${APOLLO_ADMIN_EMAIL?}    # Apollo web admin user, to be defined through externally exported env vars
      - APOLLO_ADMIN_PASSWORD=${APOLLO_ADMIN_PASSWORD?} # Apollo web admin password, to be defined through externally exported env vars
      # Core postgres DB credentials and details
      - WEBAPOLLO_DB_NAME=apollo
      - WEBAPOLLO_DB_USERNAME=apollo # Postgres user, to be defined through externally exported env vars
      - WEBAPOLLO_DB_PASSWORD=${WEBAPOLLO_DB_PASSWORD?} # Postgres password, to be defined through externally exported env vars
      # Chado postgres DB credentials and details
      - WEBAPOLLO_USE_CHADO=true
      - CHADO_DB_NAME=chado
      - CHADO_DB_USERNAME=apollo     # Postgres user, to be defined through externally exported env vars
      - CHADO_DB_PASSWORD=${CHADO_DB_PASSWORD?}     # Postgres user, to be defined through externally exported env vars
