services:
  wb-apollo-server:
    container_name: wb.apollo.server
    environment:
      - APOLLO_PATH=apollo
    extends:
      file: apollo-service-commons.yml
      service: apollo-service
    ports:
      - "8080:8080"
  apollo-import-export:
    container_name: apollo.import.export
    extends:
      file: apollo-service-commons.yml
      service: apollo-service
    volumes:
      - "./apollo_backups:/apollo_backups"
    tty: true
    stdin_open: true
    command: /bin/bash
